version: 2
updates:
  # Check for major GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Check for Go module updates
  - package-ecosystem: "gomod"
    directory: "/"  # adjust this if your go.mod file is in a subdirectory
    schedule:
      interval: "daily"
