name: Go SDK Integration Tests
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: '14 14 * * *'

jobs:
  test:
    name: Go SDK Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Get dependencies
        run: |
          go mod download

      - name: Run unit tests
        timeout-minutes: 5
        run: |
          make test

      - name: Sleep random seconds to ensure test call are not executed at exactly the same time (push and pr runs)
        run: sleep $(( ( RANDOM % 30 )  + 1 ))
        shell: bash

      - name: Run integration tests
        timeout-minutes: 60
        env:
          CLOUDSCALE_API_TOKEN: ${{ secrets.CLOUDSCALE_TOKEN }}
        if: env.CLOUDSCALE_API_TOKEN != null
        run: |
          make integration
